version: 2.1
executors:
    node8:
        docker:
            - image: circleci/node:10.16.0-browsers
        environment:
            NPM_CONFIG_PREFIX: ~/.npm-global
            CHROME_BIN: /usr/bin/google-chrome
            FIREFOX_BIN: /usr/local/bin/firefox
commands:
    setup:
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - run:
                  name: Installing Dependencies
                  command: yarn
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
            - run:
                  name: prepare test git user
                  command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"
    downstream:
        steps:
            - checkout
            - attach_workspace:
                  at: ~/
            - run:
                  name: Installing Dependencies
                  command: yarn --ignore-scripts
            - run:
                  name: prepare test git user
                  command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
    build:
        executor: node8

        steps:
            - setup
            - run:
                  name: Lint
                  command: yarn lint
            - run: yarn analyze

            # test & get code coverage
            - run:
                  name: Run tests
                  command: yarn test:ci

            - store_artifacts:
                  path: coverage

            - run:
                  name: Generate Docs
                  command: yarn docs:ci

            - persist_to_workspace:
                  root: ~/
                  paths:
                      - project/node_modules
                      - project/documentation/dist

    visual-lightest-medium:
        executor: node8

        steps:
            - downstream
            - run: yarn test:visual:ci --color=lightest --scale=medium
            - store_artifacts:
                  path: test/visual/screenshots-current

    visual-lightest-large:
        executor: node8

        steps:
            - downstream
            - run: yarn test:visual:ci --color=lightest --scale=large
            - store_artifacts:
                  path: test/visual/screenshots-current

    visual-light-medium:
        executor: node8

        steps:
            - downstream
            - run: yarn test:visual:ci --color=light --scale=medium
            - store_artifacts:
                  path: test/visual/screenshots-current

    visual-light-large:
        executor: node8

        steps:
            - downstream
            - run: yarn test:visual:ci --color=light --scale=large
            - store_artifacts:
                  path: test/visual/screenshots-current

    visual-dark-medium:
        executor: node8

        steps:
            - downstream
            - run: yarn test:visual:ci --color=dark --scale=medium
            - store_artifacts:
                  path: test/visual/screenshots-current

    visual-dark-large:
        executor: node8

        steps:
            - downstream
            - run: yarn test:visual:ci --color=dark --scale=large
            - store_artifacts:
                  path: test/visual/screenshots-current

    publish-docs:
        executor: node8

        steps:
            - downstream
            - run: cp documentation/404.html documentation/dist/
            - run: git config --global user.email "circleci@adobe.com" && git config --global user.name "CircleCI"
            - run: yarn gh-pages -d documentation/dist -m "[skip ci] update demonstration site"

workflows:
    version: 2
    build:
        jobs:
            - build
            - visual-lightest-medium:
                  requires:
                      - build
            - visual-lightest-large:
                  requires:
                      - build
            - visual-light-medium:
                  requires:
                      - build
            - visual-light-large:
                  requires:
                      - build
            - visual-dark-medium:
                  requires:
                      - build
            - visual-dark-large:
                  requires:
                      - build
            - publish-docs:
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - build
